typeset -g __p9k_cached_param_pat=$'1.20.17\C-A5.9.2\C-Azsh-5.9.2-0-gddee3e7\C-A1\C-A\'\'\C-A${#parameters[(I)POWERLEVEL9K_*]}\C-A${(%):-%n%#}\C-A$GITSTATUS_LOG_LEVEL\C-A$GITSTATUS_ENABLE_LOGGING\C-A$GITSTATUS_DAEMON\C-A$GITSTATUS_NUM_THREADS\C-A$GITSTATUS_CACHE_DIR\C-A$GITSTATUS_AUTO_INSTALL\C-A${ZLE_RPROMPT_INDENT:-1}\C-A$__p9k_sh_glob\C-A$__p9k_ksh_arrays\C-A$ITERM_SHELL_INTEGRATION_INSTALLED\C-A${PROMPT_EOL_MARK-%B%S%#%s%b}\C-A$+commands[locale]\C-A$langinfo[CODESET]\C-A${(M)VTE_VERSION:#(<1-4602>|4801)}\C-A$DEFAULT_USER\C-A$P9K_SSH\C-A$+commands[uname]\C-A$__p9k_root_dir\C-A$functions[p10k-on-init]\C-A$functions[p10k-on-pre-prompt]\C-A$functions[p10k-on-post-widget]\C-A$functions[p10k-on-post-prompt]\C-A$+commands[git]\C-A$terminfo[colors]\C-A${+_z4h_iterm_cmd}\C-A$_z4h_can_save_restore_screen${POWERLEVEL9K_INSTANT_PROMPT-\C-A}'
typeset -g __p9k_cached_param_sig=$'1.20.17\C-A5.9.2\C-Azsh-5.9.2-0-gddee3e7\C-A1\C-A\'\'\C-A1\C-Azev1ce%\C-A\C-A\C-A\C-A\C-A\C-A\C-A1\C-A0\C-A0\C-A\C-A%B%S%#%s%b\C-A1\C-AUTF-8\C-A\C-A\C-A0\C-A1\C-A/home/zev1ce/.oh-my-zsh/custom/themes/powerlevel10k\C-A\C-A\C-A\C-A\C-A1\C-A256\C-A0\C-Aquiet'
function _p9k_preinit() {
    (( 1 )) || { unfunction _p9k_preinit; return 1 }
    [[ $ZSH_VERSION == 5.9.2 ]]                      || return
    [[ -r /home/zev1ce/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh ]]             || return
    builtin source /home/zev1ce/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh _p9k_ || return
    GITSTATUS_AUTO_INSTALL=''               GITSTATUS_DAEMON=''                         GITSTATUS_CACHE_DIR=''                   GITSTATUS_NUM_THREADS=''               GITSTATUS_LOG_LEVEL=''                   GITSTATUS_ENABLE_LOGGING=''           gitstatus_start_p9k_                                              -s 1                            -u 1                          -d 1                         -c 1                        -m -1                                 -a POWERLEVEL9K
  }
_p9k_restore_state_impl() {
typeset -g -a _POWERLEVEL9K_GOENV_SOURCES=( shell local global )
typeset -g -i _POWERLEVEL9K_DISABLE_GITSTATUS=0
typeset -g -a _POWERLEVEL9K_BATTERY_DISCONNECTED_LEVEL_BACKGROUND=(  )
typeset -g -i _POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=0
typeset -g -i _POWERLEVEL9K_HASKELL_STACK_PROMPT_ALWAYS_SHOW=1
typeset -g -a _POWERLEVEL9K_BATTERY_LOW_LEVEL_BACKGROUND=(  )
typeset -g _POWERLEVEL9K_INSTANT_PROMPT=quiet
typeset -g -i _POWERLEVEL9K_LUAENV_SHOW_SYSTEM=1
typeset -g -a _POWERLEVEL9K_KUBECONTEXT_CLASSES=(  )
typeset -g _p9k_gcloud_account=''
typeset -g -a _p9k_asdf_meta_files=(  )
typeset -g -i _POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=0
typeset -g _POWERLEVEL9K_SHORTEN_FOLDER_MARKER='(.bzr|.citc|.git|.hg|.node-version|.python-version|.ruby-version|.shorten_folder_marker|.svn|.terraform|CVS|Cargo.toml|composer.json|go.mod|package.json)'
typeset -g -i _POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
typeset -g -i _POWERLEVEL9K_JENV_PROMPT_ALWAYS_SHOW=0
typeset -g -i _POWERLEVEL9K_SCALAENV_SHOW_SYSTEM=1
typeset -g -a _POWERLEVEL9K_TERRAFORM_CLASSES=(  )
typeset -g _POWERLEVEL9K_PUBLIC_IP_HOST=https://v4.ident.me/
typeset -g -i _POWERLEVEL9K_ASDF_SHOW_SYSTEM=1
typeset -g _p9k_prompt_suffix_right='${${COLUMNS::=$_p9k__clm}+}}'
typeset -g -i _p9k_term_has_href=1
typeset -g -i _POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=0
typeset -g _POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT=H:M:S
typeset -g -i _POWERLEVEL9K_GOENV_SHOW_SYSTEM=1
typeset -g _POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=')'
typeset -g -a _p9k_right_join=( 1 2 3 4 5 )
typeset -g -i _POWERLEVEL9K_LUAENV_PROMPT_ALWAYS_SHOW=0
typeset -g _POWERLEVEL9K_GITSTATUS_DIR=''
typeset -g _p9k_transient_prompt=''
typeset -g _p9k_asdf_meta_sig=''
typeset -g -a _POWERLEVEL9K_JENV_SOURCES=( shell local global )
typeset -g -i _POWERLEVEL9K_STATUS_OK=1
typeset -g _POWERLEVEL9K_SHORTEN_STRATEGY=''
typeset -g -i _p9k_num_cpus=12
typeset -g -i _POWERLEVEL9K_STATUS_ERROR_PIPE=1
typeset -g -i _POWERLEVEL9K_DOTNET_VERSION_PROJECT_ONLY=1
typeset -g -i _POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
typeset -g -A _p9k_battery_states=( [CHARGED]=green [CHARGING]=yellow [DISCONNECTED]=7 [LOW]=red )
typeset -g _POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES='virtualenv|venv|.venv|env'
typeset -g -i _POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=0
typeset -g _POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=''
typeset -g -i _POWERLEVEL9K_HIDE_BRANCH_ICON=0
typeset -g -i _POWERLEVEL9K_PHPENV_PROMPT_ALWAYS_SHOW=0
typeset -g -i _POWERLEVEL9K_SHOW_CHANGESET=0
typeset -g -a _POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status root_indicator background_jobs history time )
typeset -g -a _POWERLEVEL9K_NODENV_SOURCES=( shell local global )
typeset -g _POWERLEVEL9K_NODEENV_LEFT_DELIMITER='['
typeset -g -a _p9k_line_prefix_left=( '${_p9k__1l-${${:-${_p9k__bg::=NONE}${_p9k__i::=0}${_p9k__sss::=%f}}+}' )
typeset -g -i _p9k_timewarrior_dir_mtime=0
typeset -g -a _POWERLEVEL9K_DIR_CLASSES=( '/etc|/etc/*' ETC ⚙ '~' HOME '' '~/*' HOME_SUBFOLDER '' '*' DEFAULT '' )
typeset -g _POWERLEVEL9K_TRANSIENT_PROMPT=off
typeset -g -a _POWERLEVEL9K_GOOGLE_APP_CRED_CLASSES=( 'service_account:*' SERVICE_ACCOUNT )
typeset -g -i _POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=0
typeset -g -F _POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME_INTERVAL_SEC=1.0000000000
typeset -g -A _p9k_asdf_plugins=( )
typeset -g -a _p9k_line_suffix_left=( '%b%k$_p9k__sss%b%k%f${:-" %b%k%f"}}' )
typeset -g -i _POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=0
typeset -g -i _POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=0
typeset -g -a _p9k_line_gap_post=(  )
typeset -g -A _p9k_cache=( [$'_p9k_color prompt_background_jobs\C-@BACKGROUND\C-@0']=000. [$'_p9k_color prompt_background_jobs\C-@FOREGROUND\C-@cyan']=006. [$'_p9k_color prompt_background_jobs\C-@VISUAL_IDENTIFIER_COLOR\C-@006']=006. [$'_p9k_color prompt_context_DEFAULT\C-@BACKGROUND\C-@0']=000. [$'_p9k_color prompt_context_DEFAULT\C-@FOREGROUND\C-@yellow']=003. [$'_p9k_color prompt_context_ROOT\C-@BACKGROUND\C-@0']=000. [$'_p9k_color prompt_context_ROOT\C-@FOREGROUND\C-@yellow']=003. [$'_p9k_color prompt_dir_HOME\C-@BACKGROUND\C-@blue']=004. [$'_p9k_color prompt_dir_HOME\C-@FOREGROUND\C-@0']=000. [$'_p9k_color prompt_history\C-@BACKGROUND\C-@grey50']=244. [$'_p9k_color prompt_history\C-@FOREGROUND\C-@0']=000. [$'_p9k_color prompt_root_indicator\C-@BACKGROUND\C-@0']=000. [$'_p9k_color prompt_root_indicator\C-@FOREGROUND\C-@yellow']=003. [$'_p9k_color prompt_root_indicator\C-@VISUAL_IDENTIFIER_COLOR\C-@003']=003. [$'_p9k_color prompt_ruler\C-@BACKGROUND\C-@']=. [$'_p9k_color prompt_ruler\C-@FOREGROUND\C-@']=. [$'_p9k_color prompt_status_ERROR\C-@BACKGROUND\C-@red']=001. [$'_p9k_color prompt_status_ERROR\C-@FOREGROUND\C-@yellow1']=226. [$'_p9k_color prompt_status_ERROR\C-@VISUAL_IDENTIFIER_COLOR\C-@226']=226. [$'_p9k_color prompt_status_OK\C-@BACKGROUND\C-@0']=000. [$'_p9k_color prompt_status_OK\C-@FOREGROUND\C-@green']=002. [$'_p9k_color prompt_status_OK\C-@VISUAL_IDENTIFIER_COLOR\C-@002']=002. [$'_p9k_color prompt_time\C-@BACKGROUND\C-@7']=007. [$'_p9k_color prompt_time\C-@FOREGROUND\C-@0']=000. [$'_p9k_get_icon \C-@LEFT_SEGMENT_END_SEPARATOR']=' .' [$'_p9k_get_icon \C-@LEFT_SEGMENT_SEPARATOR']=. [$'_p9k_get_icon \C-@RULER_CHAR']=─. [$'_p9k_get_icon \C-@VCS_BRANCH_ICON']=' .' [$'_p9k_get_icon \C-@VCS_STAGED_ICON']=✚. [$'_p9k_get_icon \C-@VCS_UNSTAGED_ICON']=●. [$'_p9k_get_icon prompt_background_jobs\C-@BACKGROUND_JOBS_ICON']=⚙. [$'_p9k_get_icon prompt_background_jobs\C-@RIGHT_LEFT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_background_jobs\C-@RIGHT_MIDDLE_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_background_jobs\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@']=. [$'_p9k_get_icon prompt_background_jobs\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL']=. [$'_p9k_get_icon prompt_background_jobs\C-@RIGHT_RIGHT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_background_jobs\C-@RIGHT_SEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_background_jobs\C-@RIGHT_SUBSEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_background_jobs\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@ ']=' .' [$'_p9k_get_icon prompt_context_DEFAULT\C-@LEFT_LEFT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_context_DEFAULT\C-@LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL']=. [$'_p9k_get_icon prompt_context_DEFAULT\C-@LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@']=. [$'_p9k_get_icon prompt_context_DEFAULT\C-@LEFT_RIGHT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_context_DEFAULT\C-@LEFT_SEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_context_DEFAULT\C-@LEFT_SUBSEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_context_DEFAULT\C-@WHITESPACE_BETWEEN_LEFT_SEGMENTS\C-@ ']=' .' [$'_p9k_get_icon prompt_context_ROOT\C-@LEFT_LEFT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_context_ROOT\C-@LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL']=. [$'_p9k_get_icon prompt_context_ROOT\C-@LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@']=. [$'_p9k_get_icon prompt_context_ROOT\C-@LEFT_RIGHT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_context_ROOT\C-@LEFT_SEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_context_ROOT\C-@LEFT_SUBSEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_context_ROOT\C-@WHITESPACE_BETWEEN_LEFT_SEGMENTS\C-@ ']=' .' [$'_p9k_get_icon prompt_dir_DEFAULT\C-@FOLDER_ICON']=. [$'_p9k_get_icon prompt_dir_ETC\C-@ETC_ICON']=⚙. [$'_p9k_get_icon prompt_dir_HOME\C-@\C-A']=. [$'_p9k_get_icon prompt_dir_HOME\C-@HOME_ICON']=. [$'_p9k_get_icon prompt_dir_HOME\C-@LEFT_LEFT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_dir_HOME\C-@LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL']=. [$'_p9k_get_icon prompt_dir_HOME\C-@LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@']=. [$'_p9k_get_icon prompt_dir_HOME\C-@LEFT_RIGHT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_dir_HOME\C-@LEFT_SEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_dir_HOME\C-@LEFT_SUBSEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_dir_HOME\C-@WHITESPACE_BETWEEN_LEFT_SEGMENTS\C-@ ']=' .' [$'_p9k_get_icon prompt_dir_HOME_SUBFOLDER\C-@HOME_SUB_ICON']=. [$'_p9k_get_icon prompt_empty_line\C-@LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@']=. [$'_p9k_get_icon prompt_history\C-@RIGHT_LEFT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_history\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@']=. [$'_p9k_get_icon prompt_history\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL']=. [$'_p9k_get_icon prompt_history\C-@RIGHT_RIGHT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_history\C-@RIGHT_SEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_history\C-@RIGHT_SUBSEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_history\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@ ']=' .' [$'_p9k_get_icon prompt_os_icon\C-@LINUX_ARCH_ICON']=Arc. [$'_p9k_get_icon prompt_root_indicator\C-@RIGHT_LEFT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_root_indicator\C-@RIGHT_MIDDLE_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_root_indicator\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@']=. [$'_p9k_get_icon prompt_root_indicator\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL']=. [$'_p9k_get_icon prompt_root_indicator\C-@RIGHT_RIGHT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_root_indicator\C-@RIGHT_SEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_root_indicator\C-@RIGHT_SUBSEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_root_indicator\C-@ROOT_ICON']=⚡. [$'_p9k_get_icon prompt_root_indicator\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@ ']=' .' [$'_p9k_get_icon prompt_status_ERROR\C-@CARRIAGE_RETURN_ICON']=↵. [$'_p9k_get_icon prompt_status_ERROR\C-@RIGHT_LEFT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_status_ERROR\C-@RIGHT_MIDDLE_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_status_ERROR\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@']=. [$'_p9k_get_icon prompt_status_ERROR\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL']=. [$'_p9k_get_icon prompt_status_ERROR\C-@RIGHT_RIGHT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_status_ERROR\C-@RIGHT_SEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_status_ERROR\C-@RIGHT_SUBSEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_status_ERROR\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@ ']=' .' [$'_p9k_get_icon prompt_status_OK\C-@OK_ICON']=✔. [$'_p9k_get_icon prompt_status_OK\C-@RIGHT_LEFT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_status_OK\C-@RIGHT_MIDDLE_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_status_OK\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@']=. [$'_p9k_get_icon prompt_status_OK\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL']=. [$'_p9k_get_icon prompt_status_OK\C-@RIGHT_RIGHT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_status_OK\C-@RIGHT_SEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_status_OK\C-@RIGHT_SUBSEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_status_OK\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@ ']=' .' [$'_p9k_get_icon prompt_time\C-@RIGHT_LEFT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_time\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@']=. [$'_p9k_get_icon prompt_time\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL']=. [$'_p9k_get_icon prompt_time\C-@RIGHT_RIGHT_WHITESPACE\C-@ ']=' .' [$'_p9k_get_icon prompt_time\C-@RIGHT_SEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_time\C-@RIGHT_SUBSEGMENT_SEPARATOR']=. [$'_p9k_get_icon prompt_time\C-@TIME_ICON']=. [$'_p9k_get_icon prompt_time\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@ ']=' .' [$'_p9k_left_prompt_segment\C-@prompt_context_DEFAULT\C-@0\C-@yellow\C-@\C-@1']=$'${_p9k__n::=}${${${_p9k__bg:-0}:#NONE}:-${_p9k__n::=28}}${_p9k__n:=${${(M)${:-x000}:#x($_p9k__bg|${_p9k__bg:-0})}:+30}}${_p9k__n:=31}${_p9k__c::="${P9K_CONTENT}"}${_p9k__c::=${_p9k__c//\C-M}}${_p9k__e::=${${_p9k__1lcontext+00}:-${${(%):-$_p9k__c%1(l.1.0)}[-1]}0}}}+}${${_p9k__e:#00}:+${${_p9k_t[$_p9k__n]/<_p9k__ss>/$_p9k__ss}/<_p9k__s>/$_p9k__s}${_p9k__c}%b%K{000\\}%F{003\\} ${${:-${_p9k__s::=%F{000\\}}${_p9k__ss::=}${_p9k__sss::=%F{000\\}}${_p9k__i::=1}${_p9k__bg::=000}}+}}\C-@00' [$'_p9k_left_prompt_segment\C-@prompt_context_ROOT\C-@0\C-@yellow\C-@\C-@1']=$'${_p9k__n::=}${${${_p9k__bg:-0}:#NONE}:-${_p9k__n::=32}}${_p9k__n:=${${(M)${:-x000}:#x($_p9k__bg|${_p9k__bg:-0})}:+34}}${_p9k__n:=35}${_p9k__c::="${P9K_CONTENT}"}${_p9k__c::=${_p9k__c//\C-M}}${_p9k__e::=${${_p9k__1lcontext+00}:-${${(%):-$_p9k__c%1(l.1.0)}[-1]}0}}}+}${${_p9k__e:#00}:+${${_p9k_t[$_p9k__n]/<_p9k__ss>/$_p9k__ss}/<_p9k__s>/$_p9k__s}${_p9k__c}%b%K{000\\}%F{003\\} ${${:-${_p9k__s::=%F{000\\}}${_p9k__ss::=}${_p9k__sss::=%F{000\\}}${_p9k__i::=1}${_p9k__bg::=000}}+}}\C-@00' [$'_p9k_left_prompt_segment\C-@prompt_dir_HOME\C-@blue\C-@0\C-@\C-A\C-@2']=$'${_p9k__n::=}${${${_p9k__bg:-0}:#NONE}:-${_p9k__n::=36}}${_p9k__n:=${${(M)${:-x004}:#x($_p9k__bg|${_p9k__bg:-0})}:+38}}${_p9k__n:=39}${_p9k__c::="${P9K_CONTENT}"}${_p9k__c::=${_p9k__c//\C-M}}${_p9k__e::=${${_p9k__1ldir+00}:-${${(%):-$_p9k__c%1(l.1.0)}[-1]}0}}}+}${${_p9k__e:#00}:+${${_p9k_t[$_p9k__n]/<_p9k__ss>/$_p9k__ss}/<_p9k__s>/$_p9k__s}${_p9k__c}%b%K{004\\}%F{000\\} ${${:-${_p9k__s::=%F{004\\}}${_p9k__ss::=}${_p9k__sss::=%F{004\\}}${_p9k__i::=2}${_p9k__bg::=004}}+}}\C-@00' [$'_p9k_param \C-@LEFT_SEGMENT_END_SEPARATOR\C-@ ']=' .' [$'_p9k_param \C-@LEFT_SEGMENT_SEPARATOR\C-@\\uE0B0']='\uE0B0.' [$'_p9k_param \C-@RULER_CHAR\C-@\\u2500']='\u2500.' [$'_p9k_param \C-@VCS_BRANCH_ICON\C-@\\uE0A0 ']='\uE0A0 .' [$'_p9k_param \C-@VCS_STAGED_ICON\C-@\\u271A']='\u271A.' [$'_p9k_param \C-@VCS_UNSTAGED_ICON\C-@\\u25CF']='\u25CF.' [$'_p9k_param prompt_background_jobs\C-@BACKGROUND\C-@0']=0. [$'_p9k_param prompt_background_jobs\C-@BACKGROUND_JOBS_ICON\C-@\\u2699']='\u2699.' [$'_p9k_param prompt_background_jobs\C-@CONTENT_EXPANSION\C-@${P9K_CONTENT}']='${P9K_CONTENT}.' [$'_p9k_param prompt_background_jobs\C-@FOREGROUND\C-@cyan']=cyan. [$'_p9k_param prompt_background_jobs\C-@ICON_BEFORE_CONTENT\C-@']=. [$'_p9k_param prompt_background_jobs\C-@PREFIX\C-@']=. [$'_p9k_param prompt_background_jobs\C-@RIGHT_LEFT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_background_jobs\C-@RIGHT_MIDDLE_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_background_jobs\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_background_jobs\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_background_jobs\C-@RIGHT_RIGHT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_background_jobs\C-@RIGHT_SEGMENT_SEPARATOR\C-@\\uE0B2']='\uE0B2.' [$'_p9k_param prompt_background_jobs\C-@RIGHT_SUBSEGMENT_SEPARATOR\C-@\\uE0B3']='\uE0B3.' [$'_p9k_param prompt_background_jobs\C-@SELF_JOINED\C-@false']=false. [$'_p9k_param prompt_background_jobs\C-@SHOW_ON_UPGLOB\C-@']=. [$'_p9k_param prompt_background_jobs\C-@SUFFIX\C-@']=. [$'_p9k_param prompt_background_jobs\C-@VISUAL_IDENTIFIER_COLOR\C-@006']=006. [$'_p9k_param prompt_background_jobs\C-@VISUAL_IDENTIFIER_EXPANSION\C-@${P9K_VISUAL_IDENTIFIER}']='${P9K_VISUAL_IDENTIFIER}.' [$'_p9k_param prompt_background_jobs\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_context_DEFAULT\C-@BACKGROUND\C-@0']=0. [$'_p9k_param prompt_context_DEFAULT\C-@CONTENT_EXPANSION\C-@${P9K_CONTENT}']='${P9K_CONTENT}.' [$'_p9k_param prompt_context_DEFAULT\C-@FOREGROUND\C-@yellow']=yellow. [$'_p9k_param prompt_context_DEFAULT\C-@ICON_BEFORE_CONTENT\C-@']=. [$'_p9k_param prompt_context_DEFAULT\C-@LEFT_LEFT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_context_DEFAULT\C-@LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_context_DEFAULT\C-@LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_context_DEFAULT\C-@LEFT_RIGHT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_context_DEFAULT\C-@LEFT_SEGMENT_SEPARATOR\C-@\\uE0B0']='\uE0B0.' [$'_p9k_param prompt_context_DEFAULT\C-@LEFT_SUBSEGMENT_SEPARATOR\C-@\\uE0B1']='\uE0B1.' [$'_p9k_param prompt_context_DEFAULT\C-@PREFIX\C-@']=. [$'_p9k_param prompt_context_DEFAULT\C-@SELF_JOINED\C-@false']=false. [$'_p9k_param prompt_context_DEFAULT\C-@SHOW_ON_UPGLOB\C-@']=. [$'_p9k_param prompt_context_DEFAULT\C-@SUFFIX\C-@']=. [$'_p9k_param prompt_context_DEFAULT\C-@VISUAL_IDENTIFIER_EXPANSION\C-@${P9K_VISUAL_IDENTIFIER}']='${P9K_VISUAL_IDENTIFIER}.' [$'_p9k_param prompt_context_DEFAULT\C-@WHITESPACE_BETWEEN_LEFT_SEGMENTS\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_context_ROOT\C-@BACKGROUND\C-@0']=0. [$'_p9k_param prompt_context_ROOT\C-@CONTENT_EXPANSION\C-@${P9K_CONTENT}']='${P9K_CONTENT}.' [$'_p9k_param prompt_context_ROOT\C-@FOREGROUND\C-@yellow']=yellow. [$'_p9k_param prompt_context_ROOT\C-@ICON_BEFORE_CONTENT\C-@']=. [$'_p9k_param prompt_context_ROOT\C-@LEFT_LEFT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_context_ROOT\C-@LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_context_ROOT\C-@LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_context_ROOT\C-@LEFT_RIGHT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_context_ROOT\C-@LEFT_SEGMENT_SEPARATOR\C-@\\uE0B0']='\uE0B0.' [$'_p9k_param prompt_context_ROOT\C-@LEFT_SUBSEGMENT_SEPARATOR\C-@\\uE0B1']='\uE0B1.' [$'_p9k_param prompt_context_ROOT\C-@PREFIX\C-@']=. [$'_p9k_param prompt_context_ROOT\C-@SELF_JOINED\C-@false']=false. [$'_p9k_param prompt_context_ROOT\C-@SHOW_ON_UPGLOB\C-@']=. [$'_p9k_param prompt_context_ROOT\C-@SUFFIX\C-@']=. [$'_p9k_param prompt_context_ROOT\C-@VISUAL_IDENTIFIER_EXPANSION\C-@${P9K_VISUAL_IDENTIFIER}']='${P9K_VISUAL_IDENTIFIER}.' [$'_p9k_param prompt_context_ROOT\C-@WHITESPACE_BETWEEN_LEFT_SEGMENTS\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_dir_DEFAULT\C-@FOLDER_ICON']=. [$'_p9k_param prompt_dir_ETC\C-@ETC_ICON\C-@\\u2699']='\u2699.' [$'_p9k_param prompt_dir_HOME\C-@ANCHOR_BOLD\C-@']=. [$'_p9k_param prompt_dir_HOME\C-@BACKGROUND\C-@blue']=blue. [$'_p9k_param prompt_dir_HOME\C-@CONTENT_EXPANSION\C-@${P9K_CONTENT}']='${P9K_CONTENT}.' [$'_p9k_param prompt_dir_HOME\C-@FOREGROUND\C-@0']=0. [$'_p9k_param prompt_dir_HOME\C-@HOME_ICON']=. [$'_p9k_param prompt_dir_HOME\C-@ICON_BEFORE_CONTENT\C-@']=. [$'_p9k_param prompt_dir_HOME\C-@LEFT_LEFT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_dir_HOME\C-@LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_dir_HOME\C-@LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_dir_HOME\C-@LEFT_RIGHT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_dir_HOME\C-@LEFT_SEGMENT_SEPARATOR\C-@\\uE0B0']='\uE0B0.' [$'_p9k_param prompt_dir_HOME\C-@LEFT_SUBSEGMENT_SEPARATOR\C-@\\uE0B1']='\uE0B1.' [$'_p9k_param prompt_dir_HOME\C-@PATH_HIGHLIGHT_BOLD\C-@']=. [$'_p9k_param prompt_dir_HOME\C-@PATH_SEPARATOR\C-@/']=/. [$'_p9k_param prompt_dir_HOME\C-@PREFIX\C-@']=. [$'_p9k_param prompt_dir_HOME\C-@SELF_JOINED\C-@false']=false. [$'_p9k_param prompt_dir_HOME\C-@SHOW_ON_UPGLOB\C-@']=. [$'_p9k_param prompt_dir_HOME\C-@SUFFIX\C-@']=. [$'_p9k_param prompt_dir_HOME\C-@VISUAL_IDENTIFIER_EXPANSION\C-@${P9K_VISUAL_IDENTIFIER}']='${P9K_VISUAL_IDENTIFIER}.' [$'_p9k_param prompt_dir_HOME\C-@WHITESPACE_BETWEEN_LEFT_SEGMENTS\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_dir_HOME_SUBFOLDER\C-@HOME_SUB_ICON']=. [$'_p9k_param prompt_empty_line\C-@LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_history\C-@BACKGROUND\C-@grey50']=grey50. [$'_p9k_param prompt_history\C-@CONTENT_EXPANSION\C-@${P9K_CONTENT}']='${P9K_CONTENT}.' [$'_p9k_param prompt_history\C-@FOREGROUND\C-@0']=0. [$'_p9k_param prompt_history\C-@ICON_BEFORE_CONTENT\C-@']=. [$'_p9k_param prompt_history\C-@PREFIX\C-@']=. [$'_p9k_param prompt_history\C-@RIGHT_LEFT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_history\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_history\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_history\C-@RIGHT_RIGHT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_history\C-@RIGHT_SEGMENT_SEPARATOR\C-@\\uE0B2']='\uE0B2.' [$'_p9k_param prompt_history\C-@RIGHT_SUBSEGMENT_SEPARATOR\C-@\\uE0B3']='\uE0B3.' [$'_p9k_param prompt_history\C-@SELF_JOINED\C-@false']=false. [$'_p9k_param prompt_history\C-@SHOW_ON_UPGLOB\C-@']=. [$'_p9k_param prompt_history\C-@SUFFIX\C-@']=. [$'_p9k_param prompt_history\C-@VISUAL_IDENTIFIER_EXPANSION\C-@${P9K_VISUAL_IDENTIFIER}']='${P9K_VISUAL_IDENTIFIER}.' [$'_p9k_param prompt_history\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_os_icon\C-@LINUX_ARCH_ICON\C-@Arc']=Arc. [$'_p9k_param prompt_root_indicator\C-@BACKGROUND\C-@0']=0. [$'_p9k_param prompt_root_indicator\C-@CONTENT_EXPANSION\C-@${P9K_CONTENT}']='${P9K_CONTENT}.' [$'_p9k_param prompt_root_indicator\C-@FOREGROUND\C-@yellow']=yellow. [$'_p9k_param prompt_root_indicator\C-@ICON_BEFORE_CONTENT\C-@']=. [$'_p9k_param prompt_root_indicator\C-@PREFIX\C-@']=. [$'_p9k_param prompt_root_indicator\C-@RIGHT_LEFT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_root_indicator\C-@RIGHT_MIDDLE_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_root_indicator\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_root_indicator\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_root_indicator\C-@RIGHT_RIGHT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_root_indicator\C-@RIGHT_SEGMENT_SEPARATOR\C-@\\uE0B2']='\uE0B2.' [$'_p9k_param prompt_root_indicator\C-@RIGHT_SUBSEGMENT_SEPARATOR\C-@\\uE0B3']='\uE0B3.' [$'_p9k_param prompt_root_indicator\C-@ROOT_ICON\C-@\\u26A1']='\u26A1.' [$'_p9k_param prompt_root_indicator\C-@SELF_JOINED\C-@false']=false. [$'_p9k_param prompt_root_indicator\C-@SHOW_ON_UPGLOB\C-@']=. [$'_p9k_param prompt_root_indicator\C-@SUFFIX\C-@']=. [$'_p9k_param prompt_root_indicator\C-@VISUAL_IDENTIFIER_COLOR\C-@003']=003. [$'_p9k_param prompt_root_indicator\C-@VISUAL_IDENTIFIER_EXPANSION\C-@${P9K_VISUAL_IDENTIFIER}']='${P9K_VISUAL_IDENTIFIER}.' [$'_p9k_param prompt_root_indicator\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_ruler\C-@BACKGROUND\C-@']=. [$'_p9k_param prompt_ruler\C-@FOREGROUND\C-@']=. [$'_p9k_param prompt_status_ERROR\C-@BACKGROUND\C-@red']=red. [$'_p9k_param prompt_status_ERROR\C-@CARRIAGE_RETURN_ICON\C-@\\u21B5']='\u21B5.' [$'_p9k_param prompt_status_ERROR\C-@CONTENT_EXPANSION\C-@${P9K_CONTENT}']='${P9K_CONTENT}.' [$'_p9k_param prompt_status_ERROR\C-@FOREGROUND\C-@yellow1']=yellow1. [$'_p9k_param prompt_status_ERROR\C-@ICON_BEFORE_CONTENT\C-@']=. [$'_p9k_param prompt_status_ERROR\C-@PREFIX\C-@']=. [$'_p9k_param prompt_status_ERROR\C-@RIGHT_LEFT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_status_ERROR\C-@RIGHT_MIDDLE_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_status_ERROR\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_status_ERROR\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_status_ERROR\C-@RIGHT_RIGHT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_status_ERROR\C-@RIGHT_SEGMENT_SEPARATOR\C-@\\uE0B2']='\uE0B2.' [$'_p9k_param prompt_status_ERROR\C-@RIGHT_SUBSEGMENT_SEPARATOR\C-@\\uE0B3']='\uE0B3.' [$'_p9k_param prompt_status_ERROR\C-@SELF_JOINED\C-@false']=false. [$'_p9k_param prompt_status_ERROR\C-@SHOW_ON_UPGLOB\C-@']=. [$'_p9k_param prompt_status_ERROR\C-@SUFFIX\C-@']=. [$'_p9k_param prompt_status_ERROR\C-@VISUAL_IDENTIFIER_COLOR\C-@226']=226. [$'_p9k_param prompt_status_ERROR\C-@VISUAL_IDENTIFIER_EXPANSION\C-@${P9K_VISUAL_IDENTIFIER}']='${P9K_VISUAL_IDENTIFIER}.' [$'_p9k_param prompt_status_ERROR\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_status_OK\C-@BACKGROUND\C-@0']=0. [$'_p9k_param prompt_status_OK\C-@CONTENT_EXPANSION\C-@${P9K_CONTENT}']='${P9K_CONTENT}.' [$'_p9k_param prompt_status_OK\C-@FOREGROUND\C-@green']=green. [$'_p9k_param prompt_status_OK\C-@ICON_BEFORE_CONTENT\C-@']=. [$'_p9k_param prompt_status_OK\C-@OK_ICON\C-@\\u2714']='\u2714.' [$'_p9k_param prompt_status_OK\C-@PREFIX\C-@']=. [$'_p9k_param prompt_status_OK\C-@RIGHT_LEFT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_status_OK\C-@RIGHT_MIDDLE_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_status_OK\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_status_OK\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_status_OK\C-@RIGHT_RIGHT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_status_OK\C-@RIGHT_SEGMENT_SEPARATOR\C-@\\uE0B2']='\uE0B2.' [$'_p9k_param prompt_status_OK\C-@RIGHT_SUBSEGMENT_SEPARATOR\C-@\\uE0B3']='\uE0B3.' [$'_p9k_param prompt_status_OK\C-@SELF_JOINED\C-@false']=false. [$'_p9k_param prompt_status_OK\C-@SHOW_ON_UPGLOB\C-@']=. [$'_p9k_param prompt_status_OK\C-@SUFFIX\C-@']=. [$'_p9k_param prompt_status_OK\C-@VISUAL_IDENTIFIER_COLOR\C-@002']=002. [$'_p9k_param prompt_status_OK\C-@VISUAL_IDENTIFIER_EXPANSION\C-@${P9K_VISUAL_IDENTIFIER}']='${P9K_VISUAL_IDENTIFIER}.' [$'_p9k_param prompt_status_OK\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_time\C-@BACKGROUND\C-@7']=7. [$'_p9k_param prompt_time\C-@CONTENT_EXPANSION\C-@${P9K_CONTENT}']='${P9K_CONTENT}.' [$'_p9k_param prompt_time\C-@FOREGROUND\C-@0']=0. [$'_p9k_param prompt_time\C-@ICON_BEFORE_CONTENT\C-@']=. [$'_p9k_param prompt_time\C-@PREFIX\C-@']=. [$'_p9k_param prompt_time\C-@RIGHT_LEFT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_time\C-@RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_time\C-@RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL\C-@\C-A']=$'\C-A.' [$'_p9k_param prompt_time\C-@RIGHT_RIGHT_WHITESPACE\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_time\C-@RIGHT_SEGMENT_SEPARATOR\C-@\\uE0B2']='\uE0B2.' [$'_p9k_param prompt_time\C-@RIGHT_SUBSEGMENT_SEPARATOR\C-@\\uE0B3']='\uE0B3.' [$'_p9k_param prompt_time\C-@SELF_JOINED\C-@false']=false. [$'_p9k_param prompt_time\C-@SHOW_ON_UPGLOB\C-@']=. [$'_p9k_param prompt_time\C-@SUFFIX\C-@']=. [$'_p9k_param prompt_time\C-@TIME_ICON']=. [$'_p9k_param prompt_time\C-@VISUAL_IDENTIFIER_EXPANSION\C-@${P9K_VISUAL_IDENTIFIER}']='${P9K_VISUAL_IDENTIFIER}.' [$'_p9k_param prompt_time\C-@WHITESPACE_BETWEEN_RIGHT_SEGMENTS\C-@\C-A ']=$'\C-A .' [$'_p9k_param prompt_vcs_CLEAN\C-@CONTENT_EXPANSION\C-@x']=x. [$'_p9k_param prompt_vcs_CONFLICTED\C-@CONTENT_EXPANSION\C-@x']=x. [$'_p9k_param prompt_vcs_LOADING\C-@CONTENT_EXPANSION\C-@x']=x. [$'_p9k_param prompt_vcs_MODIFIED\C-@CONTENT_EXPANSION\C-@x']=x. [$'_p9k_param prompt_vcs_UNTRACKED\C-@CONTENT_EXPANSION\C-@x']=x. [$'_p9k_right_prompt_segment\C-@prompt_background_jobs\C-@0\C-@cyan\C-@BACKGROUND_JOBS_ICON\C-@3']=$'${_p9k__n::=}${${${_p9k__bg:-0}:#NONE}:-${_p9k__n::=16}}${_p9k__n:=${${(M)${:-x$_p9k__bg}:#x(000|000)}:+18}}${_p9k__n:=19}${_p9k__v::=⚙}${_p9k__c::="${P9K_CONTENT}"}${_p9k__c::=${_p9k__c//\C-M}}${_p9k__e::=${${_p9k__1rbackground_jobs+00}:-${${(%):-$_p9k__c%1(l.1.0)}[-1]}1}}}+}${${_p9k__e:#00}:+${_p9k_t[$_p9k__n]/<_p9k__w>/$_p9k__w}${_p9k__c}%b%K{000\\}%F{006\\}${${(M)_p9k__e:#11}:+ }$_p9k__v${${:-${_p9k__w::=%b%K{000\\}%F{006\\} %b%K{000\\}%F{006\\}}${_p9k__sss::=%b%K{000\\}%F{006\\} }${_p9k__i::=3}${_p9k__bg::=000}}+}}\C-@00' [$'_p9k_right_prompt_segment\C-@prompt_history\C-@grey50\C-@0\C-@\C-@4']=$'${_p9k__n::=}${${${_p9k__bg:-0}:#NONE}:-${_p9k__n::=20}}${_p9k__n:=${${(M)${:-x$_p9k__bg}:#x(244|244)}:+22}}${_p9k__n:=23}${_p9k__c::="${P9K_CONTENT}"}${_p9k__c::=${_p9k__c//\C-M}}${_p9k__e::=${${_p9k__1rhistory+00}:-${${(%):-$_p9k__c%1(l.1.0)}[-1]}0}}}+}${${_p9k__e:#00}:+${_p9k_t[$_p9k__n]/<_p9k__w>/$_p9k__w}${_p9k__c}%b%K{244\\}%F{000\\}${${:-${_p9k__w::=%b%K{244\\}%F{000\\} %b%K{244\\}%F{000\\}}${_p9k__sss::=%b%K{244\\}%F{000\\} }${_p9k__i::=4}${_p9k__bg::=244}}+}}\C-@00' [$'_p9k_right_prompt_segment\C-@prompt_root_indicator\C-@0\C-@yellow\C-@ROOT_ICON\C-@2']=$'${_p9k__n::=}${${${_p9k__bg:-0}:#NONE}:-${_p9k__n::=12}}${_p9k__n:=${${(M)${:-x$_p9k__bg}:#x(000|000)}:+14}}${_p9k__n:=15}${_p9k__v::=⚡}${_p9k__c::="${P9K_CONTENT}"}${_p9k__c::=${_p9k__c//\C-M}}${_p9k__e::=${${_p9k__1rroot_indicator+00}:-${${(%):-$_p9k__c%1(l.1.0)}[-1]}1}}}+}${${_p9k__e:#00}:+${_p9k_t[$_p9k__n]/<_p9k__w>/$_p9k__w}${_p9k__c}%b%K{000\\}%F{003\\}${${(M)_p9k__e:#11}:+ }$_p9k__v${${:-${_p9k__w::=%b%K{000\\}%F{003\\} %b%K{000\\}%F{003\\}}${_p9k__sss::=%b%K{000\\}%F{003\\} }${_p9k__i::=2}${_p9k__bg::=000}}+}}\C-@00' [$'_p9k_right_prompt_segment\C-@prompt_status_ERROR\C-@red\C-@yellow1\C-@CARRIAGE_RETURN_ICON\C-@1']=$'${_p9k__n::=}${${${_p9k__bg:-0}:#NONE}:-${_p9k__n::=40}}${_p9k__n:=${${(M)${:-x$_p9k__bg}:#x(001|001)}:+42}}${_p9k__n:=43}${_p9k__v::=↵}${_p9k__c::="${P9K_CONTENT}"}${_p9k__c::=${_p9k__c//\C-M}}${_p9k__e::=${${_p9k__1rstatus+00}:-${${(%):-$_p9k__c%1(l.1.0)}[-1]}1}}}+}${${_p9k__e:#00}:+${_p9k_t[$_p9k__n]/<_p9k__w>/$_p9k__w}${_p9k__c}%b%K{001\\}%F{226\\}${${(M)_p9k__e:#11}:+ }$_p9k__v${${:-${_p9k__w::=%b%K{001\\}%F{226\\} %b%K{001\\}%F{226\\}}${_p9k__sss::=%b%K{001\\}%F{226\\} }${_p9k__i::=1}${_p9k__bg::=001}}+}}\C-@00' [$'_p9k_right_prompt_segment\C-@prompt_status_OK\C-@0\C-@green\C-@OK_ICON\C-@1']=$'${_p9k__n::=}${${${_p9k__bg:-0}:#NONE}:-${_p9k__n::=8}}${_p9k__n:=${${(M)${:-x$_p9k__bg}:#x(000|000)}:+10}}${_p9k__n:=11}${_p9k__v::=✔}${_p9k__c::="${P9K_CONTENT}"}${_p9k__c::=${_p9k__c//\C-M}}${_p9k__e::=${${_p9k__1rstatus+00}:-${${(%):-$_p9k__c%1(l.1.0)}[-1]}1}}}+}${${_p9k__e:#00}:+${_p9k_t[$_p9k__n]/<_p9k__w>/$_p9k__w}${_p9k__c}%b%K{000\\}%F{002\\}${${(M)_p9k__e:#11}:+ }$_p9k__v${${:-${_p9k__w::=%b%K{000\\}%F{002\\} %b%K{000\\}%F{002\\}}${_p9k__sss::=%b%K{000\\}%F{002\\} }${_p9k__i::=1}${_p9k__bg::=000}}+}}\C-@00' [$'_p9k_right_prompt_segment\C-@prompt_time\C-@7\C-@0\C-@TIME_ICON\C-@5']=$'${_p9k__n::=}${${${_p9k__bg:-0}:#NONE}:-${_p9k__n::=24}}${_p9k__n:=${${(M)${:-x$_p9k__bg}:#x(007|007)}:+26}}${_p9k__n:=27}${_p9k__c::="${P9K_CONTENT}"}${_p9k__c::=${_p9k__c//\C-M}}${_p9k__e::=${${_p9k__1rtime+00}:-${${(%):-$_p9k__c%1(l.1.0)}[-1]}0}}}+}${${_p9k__e:#00}:+${_p9k_t[$_p9k__n]/<_p9k__w>/$_p9k__w}${_p9k__c}%b%K{007\\}%F{000\\}${${:-${_p9k__w::=%b%K{007\\}%F{000\\} %b%K{007\\}%F{000\\}}${_p9k__sss::=%b%K{007\\}%F{000\\} }${_p9k__i::=5}${_p9k__bg::=007}}+}}\C-@00' [$'prompt_status\C-@0\C-@0']=$'prompt_status_OK\C-@0\C-@green\C-@OK_ICON\C-@0\C-@\C-@0' [$'prompt_status\C-@1\C-@1']=$'prompt_status_ERROR\C-@red\C-@yellow1\C-@CARRIAGE_RETURN_ICON\C-@0\C-@\C-@10' [$'prompt_status\C-@127\C-@127']=$'prompt_status_ERROR\C-@red\C-@yellow1\C-@CARRIAGE_RETURN_ICON\C-@0\C-@\C-@1270' [$'prompt_status\C-@128\C-@128']=$'prompt_status_ERROR\C-@red\C-@yellow1\C-@CARRIAGE_RETURN_ICON\C-@0\C-@\C-@1280' [$'prompt_status\C-@130\C-@130']=$'prompt_status_ERROR\C-@red\C-@yellow1\C-@CARRIAGE_RETURN_ICON\C-@0\C-@\C-@SIGINT(2)0' )
typeset -g -F _p9k_taskwarrior_next_due=0.0000000000
typeset -g _p9k_preinit=$'function _p9k_preinit() {\n    (( 1 )) || { unfunction _p9k_preinit; return 1 }\n    [[ $ZSH_VERSION == 5.9.2 ]]                      || return\n    [[ -r /home/zev1ce/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh ]]             || return\n    builtin source /home/zev1ce/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh _p9k_ || return\n    GITSTATUS_AUTO_INSTALL=\'\'               GITSTATUS_DAEMON=\'\'                         GITSTATUS_CACHE_DIR=\'\'                   GITSTATUS_NUM_THREADS=\'\'               GITSTATUS_LOG_LEVEL=\'\'                   GITSTATUS_ENABLE_LOGGING=\'\'           gitstatus_start_p9k_                                              -s 1                            -u 1                          -d 1                         -c 1                        -m -1                                 -a POWERLEVEL9K\n  }'
typeset -g -a _p9k_asdf_meta_non_files=(  )
typeset -g -i _p9k_empty_line_idx=4
typeset -g -i _POWERLEVEL9K_CHRUBY_SHOW_ENGINE=1
typeset -g -i _POWERLEVEL9K_PLENV_SHOW_SYSTEM=1
typeset -g -i _POWERLEVEL9K_VCS_UNTRACKED_MAX_NUM=1
typeset -g _p9k_os=Linux
typeset -g -i _POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=0
typeset -g _POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER='('
typeset -g -a _POWERLEVEL9K_BATTERY_CHARGED_LEVEL_BACKGROUND=(  )
typeset -g _p9k_prompt_prefix_left='${(e)_p9k_t[7]}'
typeset -g -i _POWERLEVEL9K_TERRAFORM_SHOW_DEFAULT=0
typeset -g -a _POWERLEVEL9K_AWS_CLASSES=(  )
typeset -g -a _POWERLEVEL9K_VCS_SVN_HOOKS=( vcs-detect-changes svn-detect-changes )
typeset -g -i _POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
typeset -g -i _p9k_reset_on_line_finish=0
typeset -g -i _POWERLEVEL9K_VCS_CONFLICTED_STATE=0
typeset -g _p9k_prompt_suffix_left=$'${${COLUMNS::=$_p9k__clm}+}%{\C-[]133;B\C-G%}'
typeset -g -F _POWERLEVEL9K_GCLOUD_REFRESH_PROJECT_NAME_SECONDS=60.0000000000
typeset -g -i _POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=0
typeset -g _POWERLEVEL9K_VCS_LOADING_TEXT=loading
typeset -g -a _POWERLEVEL9K_BATTERY_STAGES=(  )
typeset -g -A _p9k_display_k=( [-1]=5 [-1/gap]=15 [-1/left]=11 [-1/left/context]=17 [-1/left/dir]=19 [-1/left/vcs]=21 [-1/left_frame]=7 [-1/right]=13 [-1/right/background_jobs]=27 [-1/right/history]=29 [-1/right/root_indicator]=25 [-1/right/status]=23 [-1/right/time]=31 [-1/right_frame]=9 [1]=5 [1/gap]=15 [1/left]=11 [1/left/context]=17 [1/left/dir]=19 [1/left/vcs]=21 [1/left_frame]=7 [1/right]=13 [1/right/background_jobs]=27 [1/right/history]=29 [1/right/root_indicator]=25 [1/right/status]=23 [1/right/time]=31 [1/right_frame]=9 [empty_line]=1 [ruler]=3 )
typeset -g -a _POWERLEVEL9K_BATTERY_LOW_STAGES=(  )
typeset -g _POWERLEVEL9K_VPN_IP_INTERFACE=''
typeset -g _p9k_timewarrior_dir=''
typeset -g -i _POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=0
typeset -g _p9k_gap_pre='${(e)_p9k_t[6]}'
typeset -g _p9k_taskwarrior_meta_sig=''
typeset -g -i _POWERLEVEL9K_RPROMPT_ON_NEWLINE=0
typeset -g -i _POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=0
typeset -g _p9k_uname=Linux
typeset -g -F _POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50.0000000000
typeset -g -i _POWERLEVEL9K_BATTERY_DISCONNECTED_HIDE_ABOVE_THRESHOLD=999
typeset -g -i _POWERLEVEL9K_DISABLE_RPROMPT=0
typeset -g _p9k_gcloud_configuration=''
typeset -g -a _POWERLEVEL9K_VCS_BACKENDS=( git )
typeset -g _POWERLEVEL9K_COLOR_SCHEME=dark
typeset -g -a _POWERLEVEL9K_HASKELL_STACK_SOURCES=( shell local )
typeset -g -i _POWERLEVEL9K_RVM_SHOW_PREFIX=0
typeset -g -i _POWERLEVEL9K_JAVA_VERSION_FULL=1
typeset -g -A icons=( [ANDROID_ICON]=And [APPLE_ICON]=OSX [ARCH_ICON]=arch [AWS_EB_ICON]='\U1F331' [AWS_ICON]=AWS [AZURE_ICON]='\u2601' [BACKGROUND_JOBS_ICON]='\u2699' [BATTERY_ICON]='\U1F50B' [CARRIAGE_RETURN_ICON]='\u21B5' [CHEZMOI_ICON]=Chez [DATE_ICON]='' [DIRENV_ICON]='\u25BC' [DISK_ICON]=hdd [DOTNET_CORE_ICON]=.NET [DOTNET_ICON]=.NET [DROPBOX_ICON]=Dropbox [ELIXIR_ICON]=elixir [ERLANG_ICON]=erl [ETC_ICON]='\u2699' [EXECUTION_TIME_ICON]='' [FAIL_ICON]='\u2718' [FLUTTER_ICON]=F [FOLDER_ICON]='' [FREEBSD_ICON]=BSD [GCLOUD_ICON]=G [GOLANG_ICON]=Go [GO_ICON]=Go [HASKELL_ICON]=hs [HISTORY_ICON]=hist [HOME_ICON]='' [HOME_SUB_ICON]='' [JAVA_ICON]='\U2615' [JULIA_ICON]=jl [KUBERNETES_ICON]='\U2388' [LARAVEL_ICON]='' [LEFT_SEGMENT_END_SEPARATOR]=' ' [LEFT_SEGMENT_SEPARATOR]='\uE0B0' [LEFT_SUBSEGMENT_SEPARATOR]='\uE0B1' [LF_ICON]=lf [LINUX_ALMALINUX_ICON]=Alma [LINUX_ALPINE_ICON]=Alp [LINUX_AMZN_ICON]=Amzn [LINUX_AOSC_ICON]=Aos [LINUX_ARCH_ICON]=Arc [LINUX_ARTIX_ICON]=Art [LINUX_CENTOS_ICON]=Cen [LINUX_COREOS_ICON]=Cor [LINUX_DEBIAN_ICON]=Deb [LINUX_DEVUAN_ICON]=Dev [LINUX_ELEMENTARY_ICON]=Elm [LINUX_ENDEAVOUROS_ICON]=Edv [LINUX_FEDORA_ICON]=Fed [LINUX_GENTOO_ICON]=Gen [LINUX_GUIX_ICON]=Guix [LINUX_ICON]=Lx [LINUX_KALI_ICON]=Kal [LINUX_MAGEIA_ICON]=Mag [LINUX_MANJARO_ICON]=Man [LINUX_MINT_ICON]=LMi [LINUX_NEON_ICON]=Neon [LINUX_NIXOS_ICON]=Nix [LINUX_OPENSUSE_ICON]=OSu [LINUX_RASPBIAN_ICON]=RPi [LINUX_RHEL_ICON]=RH [LINUX_ROCKY_ICON]=Roc [LINUX_SABAYON_ICON]=Sab [LINUX_SLACKWARE_ICON]=Sla [LINUX_UBUNTU_ICON]=Ubu [LINUX_VOID_ICON]=Vo [LOAD_ICON]=L [LOCK_ICON]='\UE0A2' [LUA_ICON]=lua [MIDNIGHT_COMMANDER_ICON]=mc [MULTILINE_FIRST_PROMPT_PREFIX]='\u256D\U2500' [MULTILINE_LAST_PROMPT_PREFIX]='\u2570\U2500 ' [MULTILINE_NEWLINE_PROMPT_PREFIX]='\u251C\U2500' [NETWORK_ICON]=IP [NIX_SHELL_ICON]=nix [NNN_ICON]=nnn [NODEJS_ICON]=Node [NODE_ICON]=Node [NORDVPN_ICON]='\UE0A2' [OK_ICON]='\u2714' [PACKAGE_ICON]=pkg [PERL_ICON]=perl [PHP_ICON]=php [POSTGRES_ICON]=postgres [PROXY_ICON]='\u2194' [PUBLIC_IP_ICON]=IP [PYTHON_ICON]=Py [RAM_ICON]=RAM [RANGER_ICON]='\u2B50' [RIGHT_SEGMENT_SEPARATOR]='\uE0B2' [RIGHT_SUBSEGMENT_SEPARATOR]='\uE0B3' [ROOT_ICON]='\u26A1' [RUBY_ICON]=Ruby [RULER_CHAR]='\u2500' [RUST_ICON]=R [SCALA_ICON]=scala [SERVER_ICON]='' [SSH_ICON]=ssh [SUDO_ICON]='' [SUNOS_ICON]=Sun [SWAP_ICON]=SWP [SWIFT_ICON]=Swift [SYMFONY_ICON]=SF [TASKWARRIOR_ICON]=task [TERRAFORM_ICON]=tf [TEST_ICON]='' [TIMEWARRIOR_ICON]=tw [TIME_ICON]='' [TODO_ICON]='\u2206' [TOOLBOX_ICON]='\u2B22' [VCS_BOOKMARK_ICON]='\u263F' [VCS_BRANCH_ICON]='\uE0A0 ' [VCS_COMMIT_ICON]='' [VCS_GIT_ARCHLINUX_ICON]='' [VCS_GIT_AZURE_ICON]='' [VCS_GIT_BITBUCKET_ICON]='' [VCS_GIT_CODEBERG_ICON]='' [VCS_GIT_DEBIAN_ICON]='' [VCS_GIT_FREEBSD_ICON]='' [VCS_GIT_FREEDESKTOP_ICON]='' [VCS_GIT_GITEA_ICON]='' [VCS_GIT_GITHUB_ICON]='' [VCS_GIT_GITLAB_ICON]='' [VCS_GIT_GNOME_ICON]='' [VCS_GIT_GNU_ICON]='' [VCS_GIT_ICON]='' [VCS_GIT_KDE_ICON]='' [VCS_GIT_LINUX_ICON]='' [VCS_GIT_SOURCEHUT_ICON]='' [VCS_HG_ICON]='' [VCS_INCOMING_CHANGES_ICON]='\u2193' [VCS_LOADING_ICON]='' [VCS_OUTGOING_CHANGES_ICON]='\u2191' [VCS_REMOTE_BRANCH_ICON]='\u2192' [VCS_STAGED_ICON]='\u271A' [VCS_STASH_ICON]='\u235F' [VCS_SVN_ICON]='' [VCS_TAG_ICON]='' [VCS_UNSTAGED_ICON]='\u25CF' [VCS_UNTRACKED_ICON]='?' [VIM_ICON]=vim [VPN_ICON]=vpn [WIFI_ICON]=WiFi [WINDOWS_ICON]=WIN [XPLR_ICON]=xplr [YAZI_ICON]='\u2B50' )
typeset -g -i _POWERLEVEL9K_STATUS_OK_PIPE=1
typeset -g -i _POWERLEVEL9K_VCS_UNSTAGED_MAX_NUM=1
typeset -g -i _POWERLEVEL9K_STATUS_CROSS=0
typeset -g _p9k_taskwarrior_data_dir=''
typeset -g -i _POWERLEVEL9K_STATUS_VERBOSE=1
typeset -g -a _POWERLEVEL9K_BATTERY_DISCONNECTED_LEVEL_FOREGROUND=(  )
typeset -g -a _POWERLEVEL9K_RBENV_SOURCES=( shell local global )
typeset -g -a _POWERLEVEL9K_BATTERY_LOW_LEVEL_FOREGROUND=(  )
typeset -g -a _POWERLEVEL9K_VCS_GIT_REMOTE_ICONS=( '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)archlinux.org)(|[/:?#]*)' VCS_GIT_ARCHLINUX_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)dev.azure.com|visualstudio.com)(|[/:?#]*)' VCS_GIT_AZURE_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)bitbucket.org)(|[/:?#]*)' VCS_GIT_BITBUCKET_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)codeberg.org)(|[/:?#]*)' VCS_GIT_CODEBERG_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)debian.org)(|[/:?#]*)' VCS_GIT_DEBIAN_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)freebsd.org)(|[/:?#]*)' VCS_GIT_FREEBSD_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)freedesktop.org)(|[/:?#]*)' VCS_GIT_FREEDESKTOP_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)gitea.com|gitea.io)(|[/:?#]*)' VCS_GIT_GITEA_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)github.com)(|[/:?#]*)' VCS_GIT_GITHUB_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)gitlab.com)(|[/:?#]*)' VCS_GIT_GITLAB_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)gnome.org)(|[/:?#]*)' VCS_GIT_GNOME_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)gnu.org)(|[/:?#]*)' VCS_GIT_GNU_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)kde.org)(|[/:?#]*)' VCS_GIT_KDE_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)kernel.org)(|[/:?#]*)' VCS_GIT_LINUX_ICON '(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)sr.ht)(|[/:?#]*)' VCS_GIT_SOURCEHUT_ICON '*' VCS_GIT_ICON )
typeset -g -i _POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME=0
typeset -g _p9k_taskwarrior_data_sig=''
typeset -g -a _p9k_left_join=( 1 2 3 )
typeset -g _POWERLEVEL9K_VCS_ACTIONFORMAT_FOREGROUND=1
typeset -g -a _POWERLEVEL9K_SCALAENV_SOURCES=( shell local global )
typeset -g -i _POWERLEVEL9K_DIR_HYPERLINK=0
typeset -g _POWERLEVEL9K_HOME_FOLDER_ABBREVIATION='~'
typeset -g -a _POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND=(  )
typeset -g -i _POWERLEVEL9K_BATTERY_VERBOSE=1
typeset -g -i _POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=0
typeset -g -a _POWERLEVEL9K_BATTERY_CHARGING_LEVEL_BACKGROUND=(  )
typeset -g -a _POWERLEVEL9K_BATTERY_DISCONNECTED_STAGES=(  )
typeset -g -A _p9k_git_slow=( )
typeset -g -i _POWERLEVEL9K_STATUS_ERROR=1
typeset -g -i _POWERLEVEL9K_DISABLE_HOT_RELOAD=0
typeset -g -i _POWERLEVEL9K_VCS_COMMITS_AHEAD_MAX_NUM=-1
typeset -g -a _p9k_line_never_empty_right=( 0 )
typeset -g -a _p9k_line_segments_left=( $'context\C-@dir\C-@vcs' )
typeset -g -i _POWERLEVEL9K_VCS_STAGED_MAX_NUM=1
typeset -g -i _POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=1
typeset -g -i _POWERLEVEL9K_CHANGESET_HASH_LENGTH=8
typeset -g -a _POWERLEVEL9K_PLENV_SOURCES=( shell local global )
typeset -g -i _POWERLEVEL9K_RVM_SHOW_GEMSET=0
typeset -g -i _p9k_ruler_idx=5
typeset -g -i _POWERLEVEL9K_PHP_VERSION_PROJECT_ONLY=0
typeset -g -a _p9k_exitcode2str=( 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 'SIGHUP(1)' 'SIGINT(2)' 'SIGQUIT(3)' 'SIGILL(4)' 'SIGTRAP(5)' 'SIGABRT(6)' 'SIGBUS(7)' 'SIGFPE(8)' 'SIGKILL(9)' 'SIGUSR1(10)' 'SIGSEGV(11)' 'SIGUSR2(12)' 'SIGPIPE(13)' 'SIGALRM(14)' 'SIGTERM(15)' 'SIGSTKFLT(16)' 'SIGCHLD(17)' 'SIGCONT(18)' 'SIGSTOP(19)' 'SIGTSTP(20)' 'SIGTTIN(21)' 'SIGTTOU(22)' 'SIGURG(23)' 'SIGXCPU(24)' 'SIGXFSZ(25)' 'SIGVTALRM(26)' 'SIGPROF(27)' 'SIGWINCH(28)' 'SIGPOLL(29)' 'SIGPWR(30)' 'SIGSYS(31)' 'SIGRTMIN(32)' 'SIGRTMIN+1(33)' 'SIGRTMIN+2(34)' 'SIGRTMIN+3(35)' 'SIGRTMIN+4(36)' 'SIGRTMIN+5(37)' 'SIGRTMIN+6(38)' 'SIGRTMIN+7(39)' 'SIGRTMIN+8(40)' 'SIGRTMIN+9(41)' 'SIGRTMIN+10(42)' 'SIGRTMIN+11(43)' 'SIGRTMIN+12(44)' 'SIGRTMIN+13(45)' 'SIGRTMIN+14(46)' 'SIGRTMIN+15(47)' 'SIGRTMAX-14(48)' 'SIGRTMAX-13(49)' 'SIGRTMAX-12(50)' 'SIGRTMAX-11(51)' 'SIGRTMAX-10(52)' 'SIGRTMAX-9(53)' 'SIGRTMAX-8(54)' 'SIGRTMAX-7(55)' 'SIGRTMAX-6(56)' 'SIGRTMAX-5(57)' 'SIGRTMAX-4(58)' 'SIGRTMAX-3(59)' 'SIGRTMAX-2(60)' 'SIGRTMAX-1(61)' 'SIGRTMAX(62)' 'SIGZERR(63)' 'SIGDEBUG(64)' 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 )
typeset -g -a _p9k_line_prefix_right=( '${_p9k__1r-${${:-${_p9k__bg::=NONE}${_p9k__i::=0}${_p9k__sss::=}}+}' )
typeset -g _POWERLEVEL9K_CHRUBY_SHOW_ENGINE_PATTERN='*'
typeset -g _POWERLEVEL9K_VCS_SHORTEN_DELIMITER=…
typeset -g -i _POWERLEVEL9K_CHRUBY_SHOW_VERSION=1
typeset -g -i _POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=1
typeset -g -a _POWERLEVEL9K_AZURE_CLASSES=(  )
typeset -g -a _POWERLEVEL9K_ASDF_SOURCES=( shell local global )
typeset -g -i _POWERLEVEL9K_PLENV_PROMPT_ALWAYS_SHOW=0
typeset -g -i _POWERLEVEL9K_NVM_PROMPT_ALWAYS_SHOW=0
typeset -g -i _POWERLEVEL9K_GOENV_PROMPT_ALWAYS_SHOW=0
typeset -g -i _POWERLEVEL9K_TERM_SHELL_INTEGRATION=1
typeset -g _p9k_vcs_side=left
typeset -g -i _p9k_vcs_index=3
typeset -g -a _POWERLEVEL9K_BATTERY_CHARGED_STAGES=(  )
typeset -g -i _POWERLEVEL9K_NODEENV_SHOW_NODE_VERSION=1
typeset -g -i _POWERLEVEL9K_VCS_CONFLICTED_MAX_NUM=1
typeset -g -i _POWERLEVEL9K_VCS_HIDE_TAGS=0
typeset -g -i _POWERLEVEL9K_PROMPT_ADD_NEWLINE=0
typeset -g _p9k_color1=0
typeset -g _p9k_gcloud_project_name=''
typeset -g -a _POWERLEVEL9K_PHPENV_SOURCES=( shell local global )
typeset -g _p9k_color2=7
typeset -g -i _POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=1
typeset -g _POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset -g _p9k_nix_shell_cond='${IN_NIX_SHELL:#0}'
typeset -g -i _POWERLEVEL9K_VPN_IP_SHOW_ALL=0
typeset -g -A _p9k_dumped_instant_prompt_sigs=( [/home/zev1ce:0:%]=1 )
typeset -g -i _POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=1
typeset -g -i _POWERLEVEL9K_STATUS_ERROR_SIGNAL=1
typeset -g -i _POWERLEVEL9K_BATTERY_LOW_THRESHOLD=10
typeset -g -a _p9k_taskwarrior_data_non_files=(  )
typeset -g -i _POWERLEVEL9K_SCALAENV_PROMPT_ALWAYS_SHOW=0
typeset -g -F _POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3.0000000000
typeset -g -a _POWERLEVEL9K_VCS_HG_HOOKS=( vcs-detect-changes )
typeset -g -i _POWERLEVEL9K_BATTERY_LOW_HIDE_ABOVE_THRESHOLD=999
typeset -g -i _POWERLEVEL9K_NODENV_SHOW_SYSTEM=1
typeset -g -a _POWERLEVEL9K_DIR_PACKAGE_FILES=( package.json composer.json )
typeset -g -i _POWERLEVEL9K_TODO_HIDE_ZERO_FILTERED=0
typeset -g -i _POWERLEVEL9K_JENV_SHOW_SYSTEM=1
typeset -g -a _POWERLEVEL9K_BATTERY_CHARGING_STAGES=(  )
typeset -g -a _POWERLEVEL9K_PUBLIC_IP_METHODS=( dig curl wget )
typeset -g -i _POWERLEVEL9K_SHOW_RULER=0
typeset -g -i _POWERLEVEL9K_PHPENV_SHOW_SYSTEM=1
typeset -g -i _POWERLEVEL9K_BATTERY_CHARGED_HIDE_ABOVE_THRESHOLD=999
typeset -g -A _p9k_taskwarrior_counters=( )
typeset -g -i _POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=90
typeset -g _POWERLEVEL9K_VI_INSERT_MODE_STRING=INSERT
typeset -g -i _POWERLEVEL9K_BATTERY_CHARGING_HIDE_ABOVE_THRESHOLD=999
typeset -g _POWERLEVEL9K_NODEENV_RIGHT_DELIMITER=']'
typeset -g -i _POWERLEVEL9K_MAX_CACHE_SIZE=10000
typeset -g _p9k_os_icon=Arc
typeset -g -i _p9k_vcs_line_index=1
typeset -g _POWERLEVEL9K_USER_TEMPLATE=%n
typeset -g -F _POWERLEVEL9K_GITSTATUS_INIT_TIMEOUT_SEC=10.0000000000
typeset -g -a _p9k_taskwarrior_meta_non_files=(  )
typeset -g _POWERLEVEL9K_ANACONDA_LEFT_DELIMITER='('
typeset -g _POWERLEVEL9K_PUBLIC_IP_NONE=''
typeset -g -a _p9k_show_on_command=(  )
typeset -g -a _POWERLEVEL9K_BATTERY_CHARGED_LEVEL_FOREGROUND=(  )
typeset -g -a _POWERLEVEL9K_KUBECONTEXT_SHORTEN=(  )
typeset -g _POWERLEVEL9K_DATE_FORMAT='%D{%d.%m.%y}'
typeset -g -a _POWERLEVEL9K_HOOK_WIDGETS=(  )
typeset -g -i _POWERLEVEL9K_RBENV_SHOW_SYSTEM=1
typeset -g -i _POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=0
typeset -g -F _POWERLEVEL9K_LOAD_CRITICAL_PCT=70.0000000000
typeset -g -i _POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL=95
typeset -g _POWERLEVEL9K_CONTEXT_TEMPLATE=%n@%m
typeset -g _POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=true
typeset -g -i _POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=1
typeset -g -a _p9k_t=( $'\n' $'%{\n%}' '' $'\n' '%b%k%f${(pl.${$((_p9k__clm-_p9k__ind))/#-*/0}..─.)}%k%f${_p9k_t[$((1+!_p9k__ind))]}' '${${:-${_p9k__x::=0}${_p9k__y::=1024}${_p9k__p::=$_p9k__lprompt$_p9k__rprompt}${_p9k__m::=$(((_p9k__x+_p9k__y)/2))}${_p9k__xy::=${${(%):-$_p9k__p%$_p9k__m(l./$_p9k__m;$_p9k__y./$_p9k__x;$_p9k__m)}##*/}}${_p9k__x::=${_p9k__xy%;*}}${_p9k__y::=${_p9k__xy#*;}}${_p9k__m::=$(((_p9k__x+_p9k__y)/2))}${_p9k__xy::=${${(%):-$_p9k__p%$_p9k__m(l./$_p9k__m;$_p9k__y./$_p9k__x;$_p9k__m)}##*/}}${_p9k__x::=${_p9k__xy%;*}}${_p9k__y::=${_p9k__xy#*;}}${_p9k__m::=$(((_p9k__x+_p9k__y)/2))}${_p9k__xy::=${${(%):-$_p9k__p%$_p9k__m(l./$_p9k__m;$_p9k__y./$_p9k__x;$_p9k__m)}##*/}}${_p9k__x::=${_p9k__xy%;*}}${_p9k__y::=${_p9k__xy#*;}}${_p9k__m::=$(((_p9k__x+_p9k__y)/2))}${_p9k__xy::=${${(%):-$_p9k__p%$_p9k__m(l./$_p9k__m;$_p9k__y./$_p9k__x;$_p9k__m)}##*/}}${_p9k__x::=${_p9k__xy%;*}}${_p9k__y::=${_p9k__xy#*;}}${_p9k__m::=$(((_p9k__x+_p9k__y)/2))}${_p9k__xy::=${${(%):-$_p9k__p%$_p9k__m(l./$_p9k__m;$_p9k__y./$_p9k__x;$_p9k__m)}##*/}}${_p9k__x::=${_p9k__xy%;*}}${_p9k__y::=${_p9k__xy#*;}}${_p9k__m::=$(((_p9k__x+_p9k__y)/2))}${_p9k__xy::=${${(%):-$_p9k__p%$_p9k__m(l./$_p9k__m;$_p9k__y./$_p9k__x;$_p9k__m)}##*/}}${_p9k__x::=${_p9k__xy%;*}}${_p9k__y::=${_p9k__xy#*;}}${_p9k__m::=$(((_p9k__x+_p9k__y)/2))}${_p9k__xy::=${${(%):-$_p9k__p%$_p9k__m(l./$_p9k__m;$_p9k__y./$_p9k__x;$_p9k__m)}##*/}}${_p9k__x::=${_p9k__xy%;*}}${_p9k__y::=${_p9k__xy#*;}}${_p9k__m::=$(((_p9k__x+_p9k__y)/2))}${_p9k__xy::=${${(%):-$_p9k__p%$_p9k__m(l./$_p9k__m;$_p9k__y./$_p9k__x;$_p9k__m)}##*/}}${_p9k__x::=${_p9k__xy%;*}}${_p9k__y::=${_p9k__xy#*;}}${_p9k__m::=$(((_p9k__x+_p9k__y)/2))}${_p9k__xy::=${${(%):-$_p9k__p%$_p9k__m(l./$_p9k__m;$_p9k__y./$_p9k__x;$_p9k__m)}##*/}}${_p9k__x::=${_p9k__xy%;*}}${_p9k__y::=${_p9k__xy#*;}}${_p9k__m::=$(((_p9k__x+_p9k__y)/2))}${_p9k__xy::=${${(%):-$_p9k__p%$_p9k__m(l./$_p9k__m;$_p9k__y./$_p9k__x;$_p9k__m)}##*/}}${_p9k__x::=${_p9k__xy%;*}}${_p9k__y::=${_p9k__xy#*;}}${_p9k__m::=$((_p9k__clm-_p9k__x-_p9k__ind-1))}}+}' $'${${_p9k__clm::=$COLUMNS}+}${${COLUMNS::=1024}+}%b%k%f${${_p9k__ind::=${${ZLE_RPROMPT_INDENT:-1}/#-*/0}}+}%{\C-[]133;A\C-G%}${_p9k_t[${_p9k__empty_line_i:-4}]}%{${_p9k__ipe-${_p9k_t[${_p9k__ruler_i:-1}]:+\n${(Q)${:-"$\'\\\\033\'\\\\[A"}}}}%}${(e)_p9k_t[${_p9k__ruler_i:-5}]}' '%b%k%F{000}%b%K{000}%F{002} ' '<_p9k__w>%b%K{000}%F{002}' '<_p9k__w>%b%K{000}%F{002} ' '<_p9k__w>%F{000}%b%K{000}%F{002} ' '%b%k%F{000}%b%K{000}%F{003} ' '<_p9k__w>%b%K{000}%F{003}' '<_p9k__w>%b%K{000}%F{003} ' '<_p9k__w>%F{000}%b%K{000}%F{003} ' '%b%k%F{000}%b%K{000}%F{006} ' '<_p9k__w>%b%K{000}%F{006}' '<_p9k__w>%b%K{000}%F{006} ' '<_p9k__w>%F{000}%b%K{000}%F{006} ' '%b%k%F{244}%b%K{244}%F{000} ' '<_p9k__w>%b%K{244}%F{000}' '<_p9k__w>%b%K{244}%F{000} ' '<_p9k__w>%F{244}%b%K{244}%F{000} ' '%b%k%F{007}%b%K{007}%F{000} ' '<_p9k__w>%b%K{007}%F{000}' '<_p9k__w>%b%K{007}%F{000} ' '<_p9k__w>%F{007}%b%K{007}%F{000} ' '%b%K{000}%F{003} ' '%b%K{000}%F{003}' '%b%K{000}<_p9k__ss>%b%K{000}%F{003} ' '%b%K{000}<_p9k__s>%b%K{000}%F{003} ' '%b%K{000}%F{003} ' '%b%K{000}%F{003}' '%b%K{000}<_p9k__ss>%b%K{000}%F{003} ' '%b%K{000}<_p9k__s>%b%K{000}%F{003} ' '%b%K{004}%F{000} ' '%b%K{004}%F{000}' '%b%K{004}<_p9k__ss>%b%K{004}%F{000} ' '%b%K{004}<_p9k__s>%b%K{004}%F{000} ' '%b%k%F{001}%b%K{001}%F{226} ' '<_p9k__w>%b%K{001}%F{226}' '<_p9k__w>%b%K{001}%F{226} ' '<_p9k__w>%F{001}%b%K{001}%F{226} ' )
typeset -g -i _POWERLEVEL9K_DIR_SHOW_WRITABLE=0
typeset -g -F _POWERLEVEL9K_PUBLIC_IP_TIMEOUT=300.0000000000
typeset -g -i _POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=0
typeset -g -a _p9k_line_suffix_right=( '$_p9k__sss%b%k%f}' )
typeset -g _p9k_prompt_prefix_right='${_p9k__1-${${_p9k__clm::=$COLUMNS}+}${${COLUMNS::=1024}+}'
typeset -g -i _p9k_timewarrior_file_mtime=0
typeset -g -F _POWERLEVEL9K_LOAD_WARNING_PCT=50.0000000000
typeset -g -A _p9k_asdf_file_info=( )
typeset -g -i _POWERLEVEL9K_VCS_COMMITS_BEHIND_MAX_NUM=-1
typeset -g -i _POWERLEVEL9K_PROMPT_ON_NEWLINE=0
typeset -g -i _POWERLEVEL9K_STATUS_HIDE_SIGNAME=0
typeset -g -i _POWERLEVEL9K_PERLBREW_SHOW_PREFIX=0
typeset -g -a _POWERLEVEL9K_VCS_GIT_HOOKS=( vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname )
typeset -g -i _POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=0
typeset -g -a _p9k_line_segments_right=( $'status\C-@root_indicator\C-@background_jobs\C-@history\C-@time' )
typeset -g -i _POWERLEVEL9K_DIR_PATH_ABSOLUTE=0
typeset -g _POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER=')'
typeset -g -i _POWERLEVEL9K_STATUS_SHOW_PIPESTATUS=1
typeset -g _p9k_uname_m=x86_64
typeset -g -i _POWERLEVEL9K_ALWAYS_SHOW_USER=0
typeset -g -i _POWERLEVEL9K_PROMPT_ADD_NEWLINE_COUNT=1
typeset -g _p9k_uname_o=GNU/Linux
typeset -g _POWERLEVEL9K_IP_INTERFACE=''
typeset -g -i _POWERLEVEL9K_VCS_RECURSE_UNTRACKED_DIRS=0
typeset -g -A _p9k_asdf_file2versions=( )
typeset -g _p9k_gcloud_project_id=''
typeset -g -i _POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=1
typeset -g -i _POWERLEVEL9K_COMMANDS_MAX_TOKEN_COUNT=64
typeset -g -a _p9k_taskwarrior_meta_files=(  )
typeset -g -F _POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0.0100000000
typeset -g _POWERLEVEL9K_VI_COMMAND_MODE_STRING=NORMAL
typeset -g -i _POWERLEVEL9K_STATUS_EXTENDED_STATES=0
typeset -g -i _POWERLEVEL9K_PERLBREW_PROJECT_ONLY=1
typeset -g -a _POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( context dir vcs )
typeset -g -i _POWERLEVEL9K_NVM_SHOW_SYSTEM=1
typeset -g _POWERLEVEL9K_PUBLIC_IP_VPN_INTERFACE=''
typeset -g -i _p9k_emulate_zero_rprompt_indent=0
typeset -g _POWERLEVEL9K_DIR_MAX_LENGTH=0
typeset -g -i _POWERLEVEL9K_DISABLE_INSTANT_PROMPT=0
typeset -g -i _POWERLEVEL9K_BATTERY_HIDE_ABOVE_THRESHOLD=999
typeset -g -a _p9k_taskwarrior_data_files=(  )
typeset -g _POWERLEVEL9K_HOST_TEMPLATE=%m
typeset -g -a _POWERLEVEL9K_BATTERY_LEVEL_FOREGROUND=(  )
typeset -g -a _POWERLEVEL9K_PYENV_SOURCES=( shell local global )
typeset -g -a _POWERLEVEL9K_BATTERY_CHARGING_LEVEL_FOREGROUND=(  )
typeset -g -i _POWERLEVEL9K_NIX_SHELL_INFER_FROM_PATH=0
typeset -g -i _POWERLEVEL9K_TODO_HIDE_ZERO_TOTAL=0
typeset -g -i _POWERLEVEL9K_LOAD_WHICH=2
typeset -g _p9k_timewarrior_file_name=''
typeset -g -i _POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_NAMESPACE=1
typeset -g -F _POWERLEVEL9K_NEW_TTY_MAX_AGE_SECONDS=5.0000000000
typeset -g -i _POWERLEVEL9K_PYENV_SHOW_SYSTEM=1
typeset -g -a _POWERLEVEL9K_LUAENV_SOURCES=( shell local global )
}
