# ╔══════════════════════════════════════════════════════════════╗
# ║             FUZZEL CONFIG — Monochrome Zinc                  ║
# ╚══════════════════════════════════════════════════════════════╝

font=JetBrainsMono Nerd Font:size=11
prompt="❯ "
icon-theme=Adwaita
fields=filename,name,generic,exec,categories,keywords
terminal=kitty
lines=10
width=40
horizontal-pad=20
vertical-pad=14
inner-pad=10
image-size-ratio=0.3
line-height=22

[border]
width=2
radius=16

[colors]
# Разметка цветов: RRGGBBAA
background=09090bf2
text=e4e4e7ff
match=ffffffff
selection=27272aff
selection-text=ffffffff
selection-match=ffffffff
border=ffffffff
